on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
        # TODO: Remove this secret when the repository has been made public
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm test
        if: runner.os != 'Linux'
        # TODO: Remove this secret when the repository has been made public
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: automated-version-bump
        with:
          commit-message: "ci: bumps version to {{version}} [skip ci]"
      - run: npm install
      - name: Build VSIX file
        uses: HaaLeo/publish-vscode-extension@v0
        id: vsixBuild
        with:
          # pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          # registryUrl: https://marketplace.visualstudio.com
          pat: "todo-replace-this-path-for-publishing"
          dryRun: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.vsixBuild.outputs.vsixPath }}
          if-no-files-found: error
