on: push

jobs:
  wanted_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Set wanted version
        run: |
          mkdir ./bin
          (cd ./lsp-translations && git describe --exact-match --tags) > ./bin/wanted_version
          cat ./bin/wanted_version
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wanted_version
          path: ./bin/wanted_version
          if-no-files-found: error

  test:
    needs: wanted_version

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   submodules: true
        #   fetch-depth: 0
      - name: Retrieve wanted version
        uses: actions/download-artifact@master
        with:
          name: wanted_version
          path: ./bin
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'

  release:
    needs: [wanted_version, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve wanted version
        uses: actions/download-artifact@master
        with:
          name: wanted_version
          path: ./bin
      - name: Bump version
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: automated-version-bump
        with:
          commit-message: "ci: bumps version to {{version}} [skip ci]"
      - run: npm install
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          packagePath: ''
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          if-no-files-found: error
