on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'

  release:
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "version-bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "ci: bumps version to {{version}} [skip ci]"
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          # pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          # registryUrl: https://marketplace.visualstudio.com
          pat: "todo-replace-this-path-for-publishing"
          dryRun: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            ${{ steps.publishToOpenVSX.outputs.vsixPath }}
